salesforce:
  #userName: ""
  #password: ""
  #securityToken : "![]"

  
  clientid: "![83qSsIN4sxR4uPT4rMaGu1nT/LwOpHMQ+KUaTh/T7lxQg0UV3j0RFI7OjYaEkl558bsFcyoGvhUgJfH0MYZf8Zj2qHDUKsNa2HvI9qXMJmmg2TPuVpGSATzp/nR5by3J]"
  secret: "![HQczY/rdhtVwgQfKYL6sHce6H591mGrroxAPoJlw27DDrKwOIBc0yzB48jSTWrnVMJgUwbVGFfYIPIfJKtAdv41VfZdjBgDBiPI4ggH4kwM=]"

Tesla:
  Username: "![adSSDMJ9cKtjXADWbwPar7VuK9CWGaPL6eb4OpD69eU=]"
  InstanceId: "![sUzzhZSCbuXxjJbptwpqaJrU0Iy5PMqTGTwlu8vjrvUnhJT+jEsdQg==]"

